### ISSUE TITLE
Purpose of balances map?

### ISSUE THREAD

**Issue by shinsyotta** [olehmisar/shieldswap#6]
What's the purpose of adding the balances in each token to a value in a map? Is that just your way of recording both balances, and you plan to parse later to get balances?

**Comment by olehmisar** [comment]
I tried to match UniswapV2 code as close as possible. `reserve0` and `reserve1` are supposed to be diffed against `token0.balance_of_public` and `token1.balance_of_public` and that's how it is determined how many tokens were swapped in/out. Unfortunately, `balance_of_public` is not available in Noir because it is marked as `unconstrained`(maybe token standard should be changed). If `balance_of_public` was not `unconstrained`, I would change this 2 lines:
```rs
let reserve0_after = reserve0.add(SafeU120::new(amount0_in)).sub(SafeU120::new(amount0_out));
let reserve1_after = reserve1.add(SafeU120::new(amount1_in)).sub(SafeU120::new(amount1_out));
```

to this:

```rs
let reserve0_after = token0.balance_of_public(context.this_address());
let reserve1_after = token1.balance_of_public(context.this_address());
```
